import {gql} from "@urql/core";
const GET_WORLD = gql`
  query getWorld($user: String!) {
    getWorld(user: $user) {
      name
      angelbonus
      logo
      money
      score
      totalangels
      lastupdate
      products{
        id
        name
        logo
        cout
        croissance
        revenu
        vitesse
        quantite
        timeleft
        managerUnlocked
        paliers{
          name
          logo
          seuil
          idcible
          ratio
          typeratio
          unlocked
        }
      }
      allunlocks{
        name
        logo
        seuil
        idcible
        ratio
        typeratio
        unlocked
      }
      upgrades{
        name
        logo
        seuil
        idcible
        ratio
        typeratio
        unlocked
      }
      angelupgrades{
        name
        logo
        seuil
        idcible
        ratio
        typeratio
        unlocked
      }
      managers{
        name
        logo
        seuil
        idcible
        ratio
        typeratio
        unlocked
      }
    }
  }
`;

export default GET_WORLD;
